name: Build Smoothie

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Smoothie
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          brew install xcbeautify create-dmg tuist

      - name: Tuist install
        run: tuist install

      - name: Tuist generate
        run: tuist generate

      - name: Build Smoothie.app
        run: |
          set -o pipefail && xcodebuild archive \
           -project ./Smoothie.xcodeproj \
           -destination "generic/platform=macOS" \
           -scheme "Smoothie" \
           -configuration Debug \
           -archivePath "./Build/Smoothie.xcarchive" \
           CODE_SIGNING_REQUIRED=NO \
           CODE_SIGNING_ALLOWED=NO \
           CODE_SIGN_IDENTITY= \
           CODE_SIGN_ENTITLEMENTS= \
           GCC_OPTIMIZATION_LEVEL=s \
           SWIFT_OPTIMIZATION_LEVEL=-O \
           GCC_GENERATE_DEBUGGING_SYMBOLS=YES \
           DEBUG_INFORMATION_FORMAT=dwarf-with-dsym | xcbeautify

      - name: Make DMG
        run: |
          create-dmg \
            --volname "Smoothie" \
            --background "./assets/graphics/dmg-background.png" \
            --window-pos 200 120 \
            --window-size 660 400 \
            --icon-size 160 \
            --icon "Smoothie.app" 180 170 \
            --hide-extension "Smoothie.app" \
            --app-drop-link 480 170 \
            --no-internet-enable \
            "./Build/Smoothie.dmg" \
            "./Build/Smoothie.xcarchive/Products/Applications/"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: Smoothie.dmg
          path: Build/Smoothie.dmg

      - name: Make ZIP
        run: |
          cp -R ./Build/Smoothie.xcarchive/Products/Applications/ ./Build/
          ditto -c -k --sequesterRsrc --keepParent ./Build/Smoothie.app ./Build/Smoothie.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Smoothie.zip
          path: Build/Smoothie.zip

      - name: Create AppCast.xml
        run: |
          ./scripts/update_appcast.sh

      - name: Upload AppCast.xml
        uses: actions/upload-artifact@v4
        with:
          name: AppCast.xml
          path: appcast.xml
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "FormalSnake"
          author_email: "kakskemail@gmail.com"
          message: "AppCast auto gen"
          # Set the files to commit - replace this with your own file paths
          add: "appcast.xml"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: daily-contribution
          # Set the Git credentials - replace this with your own secrets
          github_token: ${{ secrets.TOKEN }}
      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Daily Contribution"
          commit-message: "Daily contribution"
          branch: daily-contribution
          base: main
          # Set the pull request body - replace this with your own content
          body: "This pull request was created automatically by a GitHub Actions workflow to make an appcast."
          # Set the Git credentials - replace this with your own secrets
          token: ${{ secrets.TOKEN }}
