name: Smoothie
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
  release:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: josephrodriguez/swift-release@v1
        with:
          token: ${{ secrets.TOKEN }}
      
